Product.create!([
  {   'name': 'Heat FR350GR',   'active_ingredient': 'Saflufenacil 700g/Kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Fox Xpro 1x20 4x5 ',   'active_ingredient': 'Bixafem 125 g/L - Protioconazol 175 g/L - Trifloxistrobina 150 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Reglone 4x5 (Syngenta)',   'active_ingredient': 'Diquate 200g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Reglone 12x1 (Syngenta)',   'active_ingredient': 'Diquate 200g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Zignal 12x1 (FMC)',   'active_ingredient': 'Fluazinam 500g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Frowcide12x1',   'active_ingredient': 'Fluazinam 500g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Dimexion 12x1 (FMC)',   'active_ingredient': 'Dimetoato 400g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Thiobel 500 10x1 (Sumitomo)',   'active_ingredient': 'Cloridrato de Cartap 500g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Folpan Agricur 500 WP KG (Adama)',   'active_ingredient': 'Folpete 500g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Decis 25 EC lt (Bayer)',   'active_ingredient': 'Deltametrina 25 g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Decis 25 EC frasco (Bayer)',   'active_ingredient': 'Deltametrina 25 g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Evidence 700 WG sachê 30gr (Bayer)',   'active_ingredient': 'Imidacloprido 700g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cerconil lt (Iharabras)',   'active_ingredient': 'Tiofanato-Metílico 140g/l + Clorotalonil 350g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Sanson 40 SC 12x1 (ISK)',   'active_ingredient': 'Nicossulfuron 40g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Nippon 40 12x1 (Sumitomo)',   'active_ingredient': 'Nicossulfuron 40g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Flumyzin 500 SC 4x5 (Sumitomo)',   'active_ingredient': 'Flumioxazina 500g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Glint 1x20 4x5 ',   'active_ingredient': 'Haloxifope-P-metílico 125 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Unizeb Glory 1x20 4x5',   'active_ingredient': 'Azoxistrobina 50 g/kg - Mancozebe 700 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Verdict R 1x20 4x5',   'active_ingredient': 'Haloxifope-P-metílico 124,7 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Haloxifop CCAB 124,7 EC 1x20 4x5 ',   'active_ingredient': 'Haloxifope-P-metílico 124,7 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Paxeo (CRTVA)',   'active_ingredient': 'Diclosulam 580 g/Kg + Halauxifeno metílico 115 g/Kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Viovan',   'active_ingredient': 'Picoxistrobina 100 g/L - Protioconazol 116,7 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Blavity',   'active_ingredient': 'Fluxapiroxade 200 g/L - Protioconazol 280 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Opera',   'active_ingredient': 'Piraclostrobina 133 g/L - Epoxiconazol 50 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Ampligo',   'active_ingredient': 'Lambda-Cialotrina 50 g/L - Clorantraniliprole 100 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'MSMA',   'active_ingredient': 'MSMA 720 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Difere',   'active_ingredient': 'Equivalente em cobre metálico 350 g/L - Oxicloreto de cobre 588 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Dual Gold',   'active_ingredient': 'S-Metolacloro 960 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'CALLARIS',   'active_ingredient': 'MESOTRIONA + ATRASINA', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'OSBAR',   'active_ingredient': 'FLUAZINAN', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Roundup Original 12x1 4x5',   'active_ingredient': 'Glifosato 445 g/L - Equivalente ácido de Glifosato 370 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Abamex 12x1 L (ABAMECTINA)',   'active_ingredient': 'Abamectina 18 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Actara 250 WG 10x1 Kg',   'active_ingredient': 'Tiametoxam 250 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Adesil 12x1 L',   'active_ingredient': 'Oleo Mineral', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Adesil 4x5 L',   'active_ingredient': 'Oleo Mineral', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Assist 10x1 L',   'active_ingredient': 'Oleo Mineral', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Assist 1x20 L',   'active_ingredient': 'Oleo Mineral', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Assist 4x5 L',   'active_ingredient': 'Oleo Mineral', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Artys 20 L',   'active_ingredient': 'Picloram76 g/L - Equivalente Ácido de Picloram64 g/L - 2,4-D289 g/L - Equivalente ácido de 2,4-D 240 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Bazuka 216 SL 12x1 L (METOMIL)',   'active_ingredient': 'Metomil 216 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Bendazol 12x1 L (CARBENDAZIM)',   'active_ingredient': 'Carbendazim 500 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Bendazol 4x5 L (CARBENDAZIM)',   'active_ingredient': 'Carbendazim 500 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Camp-D 1x20 L (PICLORAM, 2,4-D)',   'active_ingredient': 'Picloram103 g/LEquivalente Ácido de Picloram64 g/L2,4-D406 g/LEquivalente ácido de 2,4-D240 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Camp-D 4x5 L (PICLORAM, 2,4-D)',   'active_ingredient': 'Picloram103 g/LEquivalente Ácido de Picloram64 g/L2,4-D406 g/LEquivalente ácido de 2,4-D240 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Carbendazim Nortox 4x5 L',   'active_ingredient': 'Carbendazim 500 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cartago 240 4x5 L (CLETODIM)',   'active_ingredient': 'Cletodim 240 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cartap BR 500 12x1 Kg (CARTAPE)',   'active_ingredient': 'Cloridrato de cartape 500 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cartarys 12x1 KG Cartap 500',   'active_ingredient': 'Cloridrato de cartape 500 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cefanol 8x3 kg (ACEFATO) (4;25)',   'active_ingredient': 'Acefato 750 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cercobin 875 WG 12x1 kg (19;15)',   'active_ingredient': 'Tiofanato-metílico 875 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cercobin 875 WG 4x5 kg',   'active_ingredient': 'Tiofanato-metílico 875 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Clipper Sinon 48x0,3 Kg - CLORIMURON',   'active_ingredient': 'Clorimurom-etílico 250 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Clorimuron Nortox 20x1',   'active_ingredient': 'Clorimurom-etílico 250 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cyptrin 250 CE 12x1 L (2;6)',   'active_ingredient': 'Cipermetrina 250 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cyptrin 250 CE 4x5 L',   'active_ingredient': 'Cipermetrina 250 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Danimen 300EC 12x1L (FENPROPATRINA)',   'active_ingredient': 'Fenpropatrina 300 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Davos 250 (Lambdacialotrina) 4x5 L',   'active_ingredient': 'Lambda-Cialotrina 250 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Dma 806 BR 4x5 L',   'active_ingredient': '2,4-D806 g/L - Equivalente ácido de 2,4-D 670 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Dual Gold 1x20 L',   'active_ingredient': 'S-Metolacloro 960 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Dual Gold 4x5',   'active_ingredient': 'S-Metolacloro 960 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Eventra 10x1 Kg (FIPRONIL)',   'active_ingredient': 'Fipronil 800 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Fascinate 200 Br (Glufosinato1x20)',   'active_ingredient': 'Glufosinato - Sal de amônio 200 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Fipronil 80 Wg Gharda (Fipronil) 12x1 Kg',   'active_ingredient': 'Fipronil 800 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Fipronil Nortox 800 WG 16x1 kg (FIPRONIL)',   'active_ingredient': 'Fipronil 800 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Flumyzin 500 SC 12x1 L',   'active_ingredient': 'Flumioxazina 500 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Galigan 240 EC 12x1 L (OXIFLUORFEM)',   'active_ingredient': 'Oxifluorfem 240 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Galil SC 12x1 L (IMIDACLOPRIDO +BIFENTRINA) ',   'active_ingredient': 'Imidacloprido 250 g/L - Bifentrina50 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Gastoxin 21x1 Kg (FOSFETO Al 570)',   'active_ingredient': 'Fosfeto de alumínio 570 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Grifo 12X1L (NICOSSULFUROM)',   'active_ingredient': 'Nicossulfurom 40 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Grifo 4X5 L (NICOSSULFUROM)',   'active_ingredient': 'Nicossulfurom 40 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Heat 10x350g',   'active_ingredient': 'Saflufenacil 700 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Lannate BR 2x10 L (METOMIL)',   'active_ingredient': 'Metomil 215 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Manfil 800 WP 10x10 kg (MANCOZEB) ',   'active_ingredient': 'Mancozebe 800 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Manfil 800 WP 20x1 kg (MANCOZEB)',   'active_ingredient': 'Mancozebe 800 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Match EC 4x5 L',   'active_ingredient': 'Lufenurom 50 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Metomil Nortox 12x1 L (METOMIL)',   'active_ingredient': 'Metomil 215 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Nomolt 150 20x250 ml',   'active_ingredient': 'Teflubenzurom 150 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Norton Nortox 1x20 L (2,4-D + PICLORAM)',   'active_ingredient': 'Equivalente ácido de 2,4-D 240 g/L - Picloram 103,5 g/L - Equivalente Ácido de Picloram 64 g/L - 2,4-D 402 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Opera 4x5 L',   'active_ingredient': 'Piraclostrobina 133 g/L - Epoxiconazol 50 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Orthocide 500 12x1 Kg (CAPTAN)',   'active_ingredient': 'Captana 500 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Penncozeb WG 1x5 kg (MANCOZEBE)',   'active_ingredient': 'Mancozebe 750 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Perito 970 SG 2x10 Kg (ACEFATO)',   'active_ingredient': 'Acefato 970 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Pacto PCT',   'active_ingredient': 'Cloransulam-metílico 840 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Privilege 1L',   'active_ingredient': 'Acetamiprido 200 g/L Piriproxifem 100 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Select 4x5 ou 1x20',   'active_ingredient': 'Cletodin 240 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Actara 250 WG 10x1 Kg',   'active_ingredient': 'Tiametoxam 250 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cruiser 350 FS 12x1 (Syngenta)',   'active_ingredient': 'Tiametoxam 350 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Glifosato Touchdown',   'active_ingredient': 'Glifosato 620 g/L - Equivalente ácido de Glifosato 500 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': '2.4 D',   'active_ingredient': '2,4-D 806 g/L - Equivalente ácido de 2,4-D 670 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Garlon',   'active_ingredient': 'Equivalente ácido de Triclopir-butotílico 480 g/L - Triclopir-butotílico 667 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Heat 10x350g',   'active_ingredient': 'Saflufenacil 700 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Verdict Max 4x5',   'active_ingredient': 'Haloxifope-P-metílico 540 g/L - Equivalente ácido de Haloxifope-P-metílico 520 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Paxeo (CRTVA)',   'active_ingredient': 'Diclosulam 580 g/Kg + Halauxifeno metílico 115 g/Kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Spider 840 Wg (CRTVA)',   'active_ingredient': 'Diclosulam 580 g/Kg ', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Lufenurom ',   'active_ingredient': 'Lufenurom 100 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Classic',   'active_ingredient': 'Clorimurom-etílico 250 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Zapp QI 620',   'active_ingredient': 'Glifosato 620 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Verdict R lt (CRTVA)',   'active_ingredient': 'Haloxifope-P-Metílico 124,7 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Dual Gold 1x20 (Syngenta)',   'active_ingredient': 'S-Metolacloro 960 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Propanil Milenia ',   'active_ingredient': 'Propanil 360 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Glifosato CHDS',   'active_ingredient': 'Equivalente ácido de Glifosato 360 g/L - Glifosato 480 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Atrazina',   'active_ingredient': 'Atrazina 500 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'PIRIPROXIFEM ',   'active_ingredient': 'Piriproxifem 100 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Verdict',   'active_ingredient': 'Equivalente ácido de Haloxifope-P-metílico 120 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Fordor Flex',   'active_ingredient': 'Isoxaflutol 750 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Mirex-S',   'active_ingredient': 'Sulfluramida 3 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Scout',   'active_ingredient': 'Glifosato 792,5 g/kg - Equivalente ácido de Glifosato 720 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Tuit Florestal',   'active_ingredient': 'Fipronil 800 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Glifosato 1x20',   'active_ingredient': 'Glifosato 480 / 620 g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Fox Xpro 4x5',   'active_ingredient': 'Bixafem 125 g/L - Protioconazol 175 g/L - Trifloxistrobina 150 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Fox Xpro 1x20',   'active_ingredient': 'Bixafem 125 g/L - Protioconazol 175 g/L - Trifloxistrobina 150 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Provence Total',   'active_ingredient': 'Indazifla 150 g/L - Isoxaflutol 450 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Evidence 700 WG pct 30 gr (Bayer)',   'active_ingredient': 'Imidacloprido 700g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Diuron CCAB 500 SC',   'active_ingredient': 'Diurom 500g/lt', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Aurora 400 EC 15x1 (FMC)',   'active_ingredient': 'Carfentrazona-etílica 400 g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cerconil 12x1 (Iharabras)',   'active_ingredient': 'Tiofanato-metílico 140 g/l + Clorotalonil 350 g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Decis 25 EC (Bayer)',   'active_ingredient': 'Deltametrina 25g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Semente TBio Duque',   'active_ingredient': 'Sementes de Trigo', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Semente Tbio Toruk',   'active_ingredient': 'Sementes de Trigo', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Semente ORS Feroz',   'active_ingredient': 'Sementes de Trigo', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Semente ORS Guardião',   'active_ingredient': 'Sementes de Trigo', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Fox X Pro',   'active_ingredient': 'Protioconazol 175g/l - Trifloxistrobina - 150 g/l - Bixafem 125g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Orkestra',   'active_ingredient': 'Fluxapiroxad 167 g/L - Piraclostrobina 333 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Standak',   'active_ingredient': 'Fipronil 250 g/l', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Engeo Pleno',   'active_ingredient': 'Tiametoxam 141 g/L - Lambda-Cialotrina 106 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Tiametoxam',   'active_ingredient': 'Tiametoxam 750 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Cercobin 875 WG ',   'active_ingredient': 'Tiofanato-metílico 875 g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Roundup Mais 1x20',   'active_ingredient': 'Glifosato 577 g/L - Equivalente ácido de Glifosato 480 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Roundup Transorb 1x20',   'active_ingredient': 'Glifosato 588 g/L - Equivalente ácido de Glifosato 480 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Dual Gold',   'active_ingredient': 'S-Metolacloro 960 g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Tordon 4x5',   'active_ingredient': '2,4-D; Picloram', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Delegade frascos 120 (CTVA)',   'active_ingredient': 'Espinetoram 250g/kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Sencor 480 (Bayer)',   'active_ingredient': 'Metribuzim 480 g/lt', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Flutriafol',   'active_ingredient': 'Flutriafol 500g/L', user_id: User.first.id, last_update_by_user_id: User.first.id   },   
  {   'name': 'Magnum',   'active_ingredient': 'Magnum 970g/Kg', user_id: User.first.id, last_update_by_user_id: User.first.id   },
])
